BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Classes" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"URL"	TEXT,
	"Credits"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Dependencies" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"SourceID"	INTEGER NOT NULL CHECK("SourceID" <> "RequiredID"),
	"RequiredID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	UNIQUE("SourceID","RequiredID"),
	FOREIGN KEY("RequiredID") REFERENCES "Classes"("ID"),
	FOREIGN KEY("SourceID") REFERENCES "Classes"("ID")
);
COMMIT;
